// Generated by CoffeeScript 1.7.1
var loading;

loading = (function() {
  function loading(data) {
    this.data = data;
  }

  loading.prototype._count = 0;

  loading.prototype._now = 0;

  loading.prototype.init = function(data) {
    var i, img, _i, _len, _results;
    this._count = data.length;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      i = data[_i];
      img = new Image();
      img.onload = this.loadimg;
      img.pe = this;
      _results.push(img.src = i.src);
    }
    return _results;
  };

  loading.prototype.loadimg = function(e) {
    this.pe._now++;
    return this.pe._progress(this.pe._now);
  };

  loading.prototype._progress = function(n) {
    this.progress(n, this._count);
    if (n === this._count) {
      return this.finished();
    }
  };

  loading.prototype.finished = function() {
    return console.log('finished');
  };

  loading.prototype.progress = function(now, count) {};

  return loading;

})();
