// Generated by CoffeeScript 1.7.1

/*
--------------------------------------------
     Begin plugs.coffee
--------------------------------------------
 */
var DMHandler, Giccoo, SHAKE_THRESHOLD, animateGo, audioEnded, audioPause, audioPlaying, auto2Audio, autoAudio, autoAudioX, backCarInside, bind360Car, bind360CarInside, bindChangeCar, changePoint, create360Car, defaultNS, deviceMotionHandler, endAudio, fBindAudio, fBindCarInside, fBindFormBtn, fBindImgs, fBindQAanswer, finishedLoad, forWeiXin, gico, hidePoint, hideResertPage, imgstouchEnd, imgstouchMove, imgstouchStart, insideUserCtrl, last_update, last_x, last_y, last_z, loadImg, loading, myK, pauseAudio, playMusic, removeEventListener, show360car, showCarInside, showNext360Img, showPlayGif, showPoint, showPrev360Img, starMove360, startMove, startTimeGo, stopAllPlay, stopMove360, touch360carend, touch360carmove, touch360carstart, _animate, _nowCar, _nowNet, _nowNex, _only, _page, _pause, _playing, _playingradio, _poList, _pointList, _speedfor, _stopmovenext, _tmove, _x, _x360, _xd, _y, _yd, _z;

Giccoo = (function() {
  function Giccoo(name) {
    this.name = name;
  }

  Giccoo.prototype.weixin = function(callback) {
    return document.addEventListener('WeixinJSBridgeReady', callback);
  };

  Giccoo.prototype.weixinHide = function() {
    return document.addEventListener('WeixinJSBridgeReady', function() {
      return WeixinJSBridge.call('hideToolbar');
    });
  };

  Giccoo.prototype.cWeek = function(week, pre) {
    if (pre == null) {
      pre = "周";
    }
    if (week === 1) {
      return pre + "一";
    }
    if (week === 2) {
      return pre + "二";
    }
    if (week === 3) {
      return pre + "三";
    }
    if (week === 4) {
      return pre + "四";
    }
    if (week === 5) {
      return pre + "五";
    }
    if (week === 6) {
      return pre + "六";
    }
    if (week === 0) {
      return pre + "日";
    }
  };

  Giccoo.prototype.getRandom = function(max, min) {
    return parseInt(Math.random() * (max - min + 1) + min);
  };

  Giccoo.prototype.getRandoms = function(l, min, max) {
    var i, idx, isEqu, num, val, _i, _j, _ref;
    num = new Array();
    for (i = _i = 0; 0 <= l ? _i < l : _i > l; i = 0 <= l ? ++_i : --_i) {
      val = Math.ceil(Math.random() * (max - min) + min);
      isEqu = false;
      for (idx = _j = 0, _ref = num.length; 0 <= _ref ? _j < _ref : _j > _ref; idx = 0 <= _ref ? ++_j : --_j) {
        if (num[idx] === val) {
          isEqu = true;
          break;
        }
      }
      if (isEqu) {
        _i--;
      } else {
        num[num.length] = val;
      }
    }
    return num;
  };

  Giccoo.prototype.getParam = function(name) {
    var r, reg;
    reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)", "i");
    r = window.location.search.substr(1).match(reg);
    if (r !== null) {
      return unescape(r[2]);
    }
    return null;
  };

  Giccoo.prototype.checkOrientation = function() {
    var orientationChange, reloadmeta;
    orientationChange = function() {
      switch (window.orientation) {
        case 0:
          return reloadmeta(640, 0);
        case 90:
          return reloadmeta(641, "no");
        case -90:
          return reloadmeta(641, "no");
      }
    };
    reloadmeta = function(px, us) {
      return setTimeout(function() {
        var viewport;
        viewport = document.getElementsByName("viewport")[0];
        return viewport.content = "width=" + px + ", user-scalable=" + us + ", target-densitydpi=device-dpi";
      }, 100);
    };
    window.addEventListener('load', function() {
      orientationChange();
      return window.onorientationchange = orientationChange;
    });
    return window.addEventListener("load", function() {
      return setTimeout(function() {
        return window.scrollTo(0, 1);
      });
    });
  };

  Giccoo.prototype.BindShare = function(content, url, pic) {
    var $ep, list;
    if (url == null) {
      url = window.location.href;
    }
    $ep = this;
    list = {
      "qweibo": "http://v.t.qq.com/share/share.php?title={title}&url={url}&pic={pic}",
      "renren": "http://share.renren.com/share/buttonshare?title={title}&link={url}&pic={pic}",
      "weibo": "http://v.t.sina.com.cn/share/share.php?title={title}&url={url}&pic={pic}",
      "qzone": "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url={url}&title={title}&pic={pic}",
      "facebook": "http://www.facebook.com/sharer/sharer.php?s=100&p[url]={url}}&p[title]={title}&p[summary]={title}&pic={pic}",
      "twitter": "https://twitter.com/intent/tweet?text={title}&pic={pic}",
      "kaixin": "http://www.kaixin001.com/rest/records.php?content={title}&url={url}&pic={pic}",
      "douban": "http://www.douban.com/share/service?bm=&image={pic}&href={url}&updated=&name={title}"
    };
    return $("[data-share]").unbind('click').bind('click', function() {
      var rep;
      if ($(this).attr('content')) {
        rep = $(this).attr('content');
        content = content.replace('{content}', rep);
      }
      return $ep.fShare(list[$(this).data('share')], content, url, pic);
    });
  };

  Giccoo.prototype.fShare = function(url, content, sendUrl, pic) {
    var backUrl, shareContent;
    if (pic == null) {
      pic = "";
    }
    content = content;
    shareContent = encodeURIComponent(content);
    pic = encodeURIComponent(pic);
    url = url.replace("{title}", shareContent);
    url = url.replace("{pic}", pic);
    backUrl = encodeURIComponent(sendUrl);
    url = url.replace("{url}", backUrl);
    return window.open(url, '_blank');
  };

  Giccoo.prototype.fBindRadio = function(e) {
    var $e;
    $e = this;
    return e.each(function(i) {
      var $div, $i;
      $div = $('<div>').addClass('radio-parent ' + $(this).attr('class'));
      $i = $('<i>');
      $(this).before($div);
      $div.addClass($(this).attr('class')).append($(this));
      $div.append($i);
      if ($(this).is(':checked')) {
        $div.addClass('on');
      }
      return $(this).change(function() {
        var $o;
        $o = $(this);
        $('[name=' + $o.attr('name') + ']').parent().removeClass('on');
        return setTimeout(function() {
          if ($o.is(':checked')) {
            return $o.parent().addClass('on');
          } else {
            return $o.parent().removeClass('on');
          }
        }, 10);
      });
    });
  };

  Giccoo.prototype.fBindCheckBox = function(e) {
    var $e;
    $e = this;
    return e.each(function(i) {
      var $div, $i;
      $div = $('<div>').addClass('checkbox-parent ' + $(this).attr('class'));
      $i = $('<i>');
      $(this).before($div);
      $div.addClass($(this).attr('class')).append($(this));
      $div.append($i);
      return $(this).change(function() {
        var $o;
        $o = $(this);
        return setTimeout(function() {
          if ($o.is(':checked')) {
            return $o.parent().addClass('on');
          } else {
            return $o.parent().removeClass('on');
          }
        }, 10);
      });
    });
  };

  Giccoo.prototype.fBindSelect = function(e) {
    var $e;
    $e = this;
    return e.each(function(i) {
      var $div, $i, $span;
      $div = $('<div>').addClass('select-parent');
      $span = $('<span>');
      $i = $('<i>');
      $(this).before($div);
      $div.addClass($(this).attr('class')).append($(this));
      if ($(this).val()) {
        $div.append($span.append($(this).find('option[value="' + $(this).val() + '"]').text()));
      } else {
        $div.append($span.append($(this).find('option').text()));
      }
      $div.append($i);
      return $(this).change(function() {
        var $o;
        $o = $(this);
        return setTimeout(function() {
          return $e.fChangeSelectVal($o);
        }, 10);
      });
    });
  };

  Giccoo.prototype.fChangeSelectVal = function(o) {
    if ($(o).val()) {
      return $(o).next().html($(o).find('option[value="' + $(o).val() + '"]').text());
    } else {
      return $(o).next().html($(o).find('option').text());
    }
  };

  Giccoo.prototype.mobilecheck = function() {
    if (navigator.userAgent.match(/Android/i) || navigator.userAgent.match(/webOS/i) || navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iPod/i) || navigator.userAgent.match(/BlackBerry/i) || navigator.userAgent.match(/Windows Phone/i)) {
      return true;
    }
    return false;
  };

  Giccoo.prototype.fBindOrientation = function() {
    window.addEventListener('deviceorientation', this.orientationListener, false);
    window.addEventListener('MozOrientation', this.orientationListener, false);
    return window.addEventListener('devicemotion', this.orientationListener, false);
  };

  Giccoo.prototype.orientationListener = function(evt) {
    var alpha, beta, gamma;
    if (!evt.gamma && !evt.beta) {
      evt.gamma = evt.x * (180 / Math.PI);
      evt.beta = evt.y * (180 / Math.PI);
      evt.alpha = evt.z * (180 / Math.PI);
    }
    gamma = evt.gamma;
    beta = evt.beta;
    alpha = evt.alpha;
    if (evt.accelerationIncludingGravity) {
      gamma = event.accelerationIncludingGravity.x * 10;
      beta = -event.accelerationIncludingGravity.y * 10;
      alpha = event.accelerationIncludingGravity.z * 10;
    }
    if (this._lastGamma !== gamma || this._lastBeta !== beta) {
      oriencallback(beta.toFixed(2), gamma.toFixed(2), alpha !== (null ? alpha.toFixed(2) : 0), gamma, beta);
      this._lastGamma = gamma;
      return this._lastBeta = beta;
    }
  };

  Giccoo.prototype.fBindShake = function() {
    if (window.DeviceMotionEvent) {
      return window.addEventListener('devicemotion', deviceMotionHandler, false);
    }
  };

  Giccoo.prototype.fUnBindShake = function() {
    if (window.DeviceMotionEvent) {
      return window.removeEventListener('devicemotion', deviceMotionHandler, false);
    }
  };

  return Giccoo;

})();

SHAKE_THRESHOLD = 1000;

if (navigator.userAgent.indexOf('iPhone') > -1) {
  SHAKE_THRESHOLD = 700;
} else if (navigator.userAgent.indexOf('QQ') > -1) {
  SHAKE_THRESHOLD = 1000;
}

last_update = 0;

_x = _y = _z = last_x = last_y = last_z = 0;

DMHandler = function() {};

deviceMotionHandler = function(eventData) {
  var acceleration, curTime, diffTime, speed;
  acceleration = eventData.accelerationIncludingGravity;
  curTime = new Date().getTime();
  if ((curTime - last_update) > 50) {
    diffTime = parseInt(curTime - last_update);
    last_update = curTime;
    _x = acceleration.x;
    _y = acceleration.y;
    _z = acceleration.z;
    speed = Math.abs(_x + _y + _z - last_x - last_y - last_z) / diffTime * 10000;
    console.log(_x, _y, _z);
    if (speed > SHAKE_THRESHOLD) {
      DMHandler();
    }
    last_x = _x;
    last_y = _y;
    return last_z = _z;
  }
};

gico = new Giccoo('normal');


/*
--------------------------------------------
     Begin loading.coffee
--------------------------------------------
 */

loading = (function() {
  function loading(data) {
    this.data = data;
    this.list = [];
  }

  loading.prototype._count = 0;

  loading.prototype._now = 0;

  loading.prototype.init = function(data) {
    var i, img, _i, _len, _results;
    this._count = data.length;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      i = data[_i];
      img = new Image();
      img.onload = this.loadimg;
      img.pe = this;
      img.src = i.src;
      _results.push(this.list[i.id] = img);
    }
    return _results;
  };

  loading.prototype.loadimg = function(e) {
    this.pe._now++;
    return this.pe._progress(this.pe._now);
  };

  loading.prototype._progress = function(n) {
    this.progress(n, this._count);
    if (n >= this._count) {
      return this.finished();
    }
  };

  loading.prototype.finished = function() {
    return console.log('finished');
  };

  loading.prototype.progress = function(now, count) {};

  return loading;

})();


/*
--------------------------------------------
     Begin main.coffee
--------------------------------------------
 */

loading = new loading();

_playing = false;

_pause = false;

_playingradio = {
  car: "",
  idx: -1,
  idt: -1
};

_page = "360";

_pointList = {
  "a32": [
    {
      times: "23''",
      header: "s-1",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-1.mp3",
      name: "胡玲",
      title: "凤凰卫视北京站首席记者",
      t1: "更有型的外观设计",
      t2: "全新奥迪A3 Sportback拥有轿跑般的⻋顶线条 硬朗的⻋⾝腰线,以及动感的掀背式造型。独特的箭头造型前⼤灯和简洁的分体式尾灯宣扬着你毫不妥协的态度。短暂的⺫光接触,便⾜以令你⼼驰神往。",
      t3: "全新奥迪A3 Sportback与全新奥迪A3 Limousine的区别在于哪⾥里?",
      q1: "轿跑般的⻋顶线条、硬朗的⻋⾝腰线,以及动感的掀背式造型",
      q2: "除了⼀个是两厢,⼀个是三厢以外,没什么区别",
      answer: 0
    }, {
      times: "22''",
      header: "s-2",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-2.mp3",
      name: "李黎",
      title: "网易副总裁",
      t1: "更轻盈的奥迪ultra轻量技术",
      t2: "全新奥迪A3 Sportback使⽤ultra轻量化⻋⾝技术,运⽤创新复合材料,提升⻋⾝的钢性,同时减少不必要的能量损耗,实现了灵活操控与安全强度的完美统⼀,带来更绿色的驾乘体验。",
      t3: "全新奥迪A3 Sportback使⽤的ultra轻量化⻋⾝技术,有什么作⽤?",
      q1: "全部使⽤碳纤维材质,⼤幅降低⻋⾝重量",
      q2: "提升⻋⾝的钢性,减少不必要的能量损",
      answer: 1
    }
  ],
  "a33": [
    {
      times: "15''",
      header: "l-1",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-1.mp3",
      name: "崔莉莉",
      title: "搜狐集团高级副总裁",
      t1: "更有型的外观设计",
      t2: "全新奥迪A3 Limousine将经典三厢设计与双⻔轿跑理念完美结合,理所当然配备的LED⻋灯,性感明快的腰线,与两厢相⽐更加锐利的上升式尾部造型,都赋予了TA更加灵活、动 感的⾝姿。",
      t3: "与两厢版相⽐,全新奥迪A3 Limousine外观的最⼤特点是什么?",
      q1: "锐利的上升式尾部造型",
      q2: "配备的LED⻋灯",
      answer: 0
    }, {
      times: "22''",
      header: "l-2",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-2.mp3",
      name: "张京秋",
      title: "爱卡汽车创始人",
      t1: "更轻盈的奥迪ultra轻量技术",
      t2: "驾驶全新奥迪A3 Limousine时,灵活是印⼊脑海的第⼀印象,强劲则是随之⽽来的直观感受。奥迪ultra轻量化技术,使⽤复合材料让⻋⾝更轻,但更加坚固安全,只为给你带来完美的驾驭感受。",
      t3: "全新奥迪A3 Limousine使⽤的奥迪ultra轻量化技术,究竟是什么让⻋⾝更轻?",
      q1: "创新材料和⻋⾝框架",
      q2: "碳纤维",
      answer: 0
    }
  ]
};

_poList = {
  "a32": [
    {
      times: "14''",
      header: "s-3",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-3.mp3",
      name: "张齐",
      title: "凤凰网汽车事业部总经理",
      t1: "更智能的MMI®多媒体交互系统",
      t2: "全新奥迪A3 Sportback搭载新⼀代MMI®多媒体交互系统。特有的触控轮,让导航和打电话变得轻松惬意。相信有那么⼀瞬间,你将体会到亲⼿触碰未来的感觉。",
      t3: "新⼀代MMI®系统怎样使全新奥迪A3 Sportback重新定义了⻋载信息娱乐系统?",
      q1: "新⼀代MMI®按钮更少,操作更直观便捷",
      q2: "新⼀代MMI®可以显⽰示⻋辆当前的时速",
      answer: 0
    }, {
      times: "20''",
      header: "s-4",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-4.mp3",
      name: "刘晓科",
      title: "新浪全国商业运营总经理",
      t1: "更浑厚的Bang&Olufsen音响",
      t2: "为全新奥迪A3 Sportback度⾝定制的B&O音响系统,配备5.1环绕⽴体声和14个扬声器,震撼的效果仿佛⾝临其境。音量可随⻋速和噪音变化⾃动调整,让车舱秒变音乐秀场。",
      t3: "为全新奥迪A3 Sportback度⾝定制的B&O音响系统,有什么独特作⽤?",
      q1: "音量可随⻋速和噪音变化⾃动调整",
      q2: "可以进⾏录音",
      answer: 0
    }, {
      times: "19''",
      header: "s-5",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-5.mp3",
      name: "云鹏",
      title: "极驾客执行主编",
      t1: "更敏捷的S tronic®双离合变速器",
      t2: "全新奥迪A3 Sportback配备的Stronic®双离合变速箱兼顾了更强动⼒与更低能耗。与TFSI® 发动机的完美搭配,将整⻋的动⼒与操控提升到了全新⾼度,充分释放你的驾驭激情。",
      t3: "全新奥迪A3 Sportback配备的S tronic®双离合变速箱,有什么特点?",
      q1: "有效减少变速箱内齿轮机构磨损",
      q2: "将整⻋的动⼒与操控提升到全新⾼度,并保证相对较低的能耗",
      answer: 1
    }, {
      times: "26''",
      header: "s-6",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/s-6.mp3",
      name: "韩路",
      title: "汽车之家编辑部总监",
      t1: "更强劲的TFSI®发动机",
      t2: "全新奥迪A3 Sportback搭载的1.4 TFSI®发动机,将FSI®燃油直喷的⾼效与涡轮增压的⾼扭矩输出集于⼀⾝,动⼒输出强劲⽽流畅。启动发动机的⼀刻,澎湃动⼒早已蓄势待发。",
      t3: "全新奥迪A3 Sportback搭载的是什么发动机?",
      q1: "1.4/1.8 TFSI汽油直喷涡轮增压发动机",
      q2: "1.4/1.8 FSI汽油直喷发动机",
      answer: 0
    }
  ],
  "a33": [
    {
      times: "16''",
      header: "l-3",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-3.mp3",
      name: "邹硕",
      title: "搜狐主编",
      t1: "更智能的MMI®多媒体交互系统",
      t2: "全新奥迪A3 Limousine搭载新⼀代MMI®多媒体交互系统, 独特的MMI ®触控轮,可⽀持⼿写⽅方式输⼊,让导航和打电话变得轻松惬意。指尖轻巧滑动,⼀切尽在掌握。",
      t3: "是什么装置,让全新奥迪A3 Limousine搭载的MMI®多媒体交互系统轻松便捷?",
      q1: "独⽴⼿写输⼊板",
      q2: "独特的MMI ®触控轮",
      answer: 1
    }, {
      times: "21''",
      header: "l-4",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-4.mp3",
      name: "周全",
      title: "新浪全国商业运营总经理",
      t1: "更浑厚的Bang&Olufsen音响",
      t2: "全新奥迪A3 Limousine搭载丹⻨麦顶级B&O音响系统,配备5.1环绕⽴体声和14个扬声器,为你带来震撼的视听感受。系统可根据⾼低音呈现不同的LED照明效果,使客舱的时尚氛围动感即现。",
      t3: "全新奥迪A3 Limousine搭载的什么音响系统,具备可根据⾼低音呈现不同LED效果?",
      q1: "丹⻨麦顶级B&O音响系统",
      q2: "BOSE音响系统",
      answer: 0
    }, {
      times: "18''",
      header: "l-5",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-5.mp3",
      name: "王洪浩",
      title: "易车网编辑运营中心总经理",
      t1: "更敏捷的S tronic®双离合变速器",
      t2: "0.2秒是全新奥迪A3 Limousine换挡的全过程时间。搭载Stronic®双离合变速器的Ta能在你毫⽆察觉的情况下完成⾼效换挡动作,你⼏乎感觉不到任何顿挫感。",
      t3: "全新奥迪A3 Limousine搭载的S tronic®双离合变速器,给你最直观的感受是?",
      q1: "换挡迅速且没有任何顿挫感",
      q2: "驾驶中不会感觉到颠簸",
      answer: 0
    }, {
      times: "22''",
      header: "l-6",
      mp3: "http://audi.mconnect.cn/A3-wechat/mp3/l-6.mp3",
      name: "闫闯",
      title: "汽车之家编辑",
      t1: "更强劲的TFSI®发动机",
      t2: "全新奥迪A3 Limousine搭载的新⼀代1.8T 发动机,匹配奥迪可变⽓门升程系统,输出⾼效动⼒的同时保证较低的油耗。什么是更强劲? 踩下油⻔,⼀切不⾔⾃明。",
      t3: "全新奥迪A3 Limousine可在动⼒强劲的同时,保证较低油耗,是搭载了什么装置?",
      q1: "汽缸按需运⾏系统",
      q2: "奥迪可变⽓门升程系统",
      answer: 1
    }
  ]
};

document.addEventListener('WeixinJSBridgeReady', function() {
  return forWeiXin();
});

forWeiXin = function() {
  $("#qafs").attr('src', 'img/qa.png');
  $(".car360inside .qatitle").click(function() {
    $(".weixinshare").show();
    return $("body").addClass("open");
  });
  return $(".weixinshare")[0].addEventListener('touchstart', function(e) {
    e.preventDefault();
    $(".weixinshare").hide();
    return $("body").removeClass("open");
  });
};

$(document).ready(function() {
  if ($("[data-rel=resertpage]").length <= 0) {
    bind360Car();
    fBindQAanswer();
    fBindAudio();
    fBindImgs();
  }
  bindChangeCar();
  loadImg();
  fBindCarInside();
  fBindFormBtn();
  bind360CarInside();
  $(".car-1").click(function() {
    _page = "360";
    create360Car('a33');
    return show360car();
  });
  $(".car-2").click(function() {
    _page = "360";
    create360Car('a32');
    return show360car();
  });
  $(".backhome").click(function() {
    $(".car360,.carsideinfo,.car360inside,.resertpage").removeClass('fadeInDownBig').addClass('fadeOutUpBig');
    $(".homepage").removeClass('fadeOutUpBig').addClass('fadeInDownBig');
    stopAllPlay();
    $("#audio")[0].pause();
    return setTimeout(function() {
      return $(".car360,.carsideinfo,.car360inside,.resertpage").hide();
    }, 500);
  });
  myK("province").innerHTML = fGetHTMLP();
  myK("city").innerHTML = fGetHTMLC(myK("province").value);
  myK("dealer").innerHTML = fGetHTMLS(myK("province").value, myK("city").value);
  myK("province").onchange = function() {
    return setTimeout(function() {
      myK("city").innerHTML = fGetHTMLC(myK("province").value);
      myK("dealer").innerHTML = fGetHTMLS(myK("province").value, myK("city").value);
      $('#city').change();
      return $('#dealer').change();
    }, 20);
  };
  myK("city").onchange = function() {
    return setTimeout(function() {
      myK("dealer").innerHTML = fGetHTMLS(myK("province").value, myK("city").value);
      return $('#dealer').change();
    }, 20);
  };
  gico.fBindSelect($("select"));
  gico.fBindRadio($("input[type=radio]"));
  return $(".openresert").click(function() {
    $(".resertpage").removeClass("fadeOutUpBig").show().addClass('animated fadeInDownBig');
    return false;
  });
});

myK = function(id) {
  return document.getElementById(id);
};

hideResertPage = function() {
  $(".resertpage").removeClass('animated fadeInDownBig');
  $(".resertpage").addClass('animated fadeOutUpBig');
  return setTimeout(function() {
    return $(".resertpage").hide();
  }, 500);
};

loadImg = function() {
  loading.finished = function() {
    return finishedLoad();
  };
  return loading.init([
    {
      src: "img/logo.png",
      id: "logo"
    }, {
      src: "img/car-1.png",
      id: "car-1"
    }, {
      src: "img/car-2.png",
      id: "car-2"
    }, {
      src: "img/index-text.png",
      id: "index-text"
    }, {
      src: "img/index-sound.png",
      id: "index-sound"
    }, {
      src: "img/index-chance.png",
      id: "index-chance"
    }, {
      src: "img/point.png",
      id: "point"
    }, {
      src: "img/icon-sound.png",
      id: "icon-sound"
    }, {
      src: "img/sound-w.png",
      id: "sound-w"
    }, {
      src: "img/qa.png",
      id: "qa"
    }, {
      src: "img/register.png",
      id: "register"
    }, {
      src: "img/bg-car.jpg",
      id: "bg-car"
    }, {
      src: "img/a3s-back.png",
      id: "a3s-back"
    }, {
      src: "img/a3l-back.png",
      id: "a3l-back"
    }, {
      src: "img/l-1.jpg",
      id: "l-1"
    }, {
      src: "img/l-2.jpg",
      id: "l-2"
    }, {
      src: "img/l-3.jpg",
      id: "l-3"
    }, {
      src: "img/l-4.jpg",
      id: "l-4"
    }, {
      src: "img/l-5.jpg",
      id: "l-5"
    }, {
      src: "img/l-6.jpg",
      id: "l-6"
    }, {
      src: "img/s-1.jpg",
      id: "s-1"
    }, {
      src: "img/s-2.jpg",
      id: "s-2"
    }, {
      src: "img/s-3.jpg",
      id: "s-3"
    }, {
      src: "img/s-4.jpg",
      id: "s-4"
    }, {
      src: "img/s-5.jpg",
      id: "s-5"
    }, {
      src: "img/s-6.jpg",
      id: "s-6"
    }
  ]);
};

finishedLoad = function() {
  console.log("finished");
  $(".loading").hide();
  return animateGo();
};

animateGo = function() {
  return $("[data-animate]").each(function() {
    return $(this).addClass($(this).data('animate'));
  });
};

_animate = false;

fBindImgs = function() {
  if ($("#img-list").length >= 0) {
    console.log("band");
    $("#img-list")[0].addEventListener('touchstart', imgstouchStart);
    $("#img-list")[0].addEventListener('touchmove', imgstouchMove);
    $("#img-list")[0].addEventListener('touchend', imgstouchEnd);
    $("#img-list .left").click(function() {
      return startMove('right');
    });
    $("#img-list .right").click(function() {
      return startMove('left');
    });
    return $("#img-list .bottom").click(function() {
      return startMove('up');
    });
  }
};

_xd = 0;

_yd = 0;

imgstouchStart = function(e) {
  _xd = e.touches[0].pageX;
  return _yd = e.touches[0].pageY;
};

imgstouchMove = function(e) {
  var x, y;
  x = e.touches[0].pageX;
  y = e.touches[0].pageY;
  e.preventDefault();
  if (Math.round(_yd - y) > 20) {
    console.log("up?");
    startMove('up');
    return removeEventListener();
  } else if (Math.round(_yd - y) < -20) {
    console.log("down?");
    startMove('down');
    return removeEventListener();
  } else if (Math.round(_xd - x) > 20) {
    console.log("left?");
    startMove('left');
    return removeEventListener();
  } else if (Math.round(_xd - x) < -20) {
    console.log("rigth?");
    startMove('right');
    return removeEventListener();
  }
};

imgstouchEnd = function(e) {
  console.log("addEventListener");
  return $("#img-list")[0].addEventListener('touchmove', imgstouchMove);
};

removeEventListener = function() {
  return $("#img-list")[0].removeEventListener('touchmove', imgstouchMove);
};

_nowNex = 0;

startMove = function(fx) {
  var $e, $ep, classs, model;
  $e = $("#img-list .img-list");
  $ep = $("#img-list .movectrl");
  model = $e.attr('model');
  if (model === fx) {
    return '';
  }
  $(".right", $ep).show();
  $(".left", $ep).show();
  $(".bottom", $ep).show();
  classs = "fadeInRightBig fadeInLeftBig fadeInDownBig fadeInUpBig";
  $("[remove]", $e).removeClass(classs);
  $("[remove]", $e).each(function() {
    var $removethis;
    $(this).addClass($(this).attr('remove'));
    $removethis = $(this);
    return setTimeout(function() {
      return $removethis.remove();
    }, 1500);
  });
  _nowNex = 0;
  if (fx === 'left' && model === 'right') {
    $e.attr('model', 'center');
    return changePoint('point3');
  } else if (fx === 'right' && model === 'left') {
    $e.attr('model', 'center');
    return changePoint('point3');
  } else if (fx === 'left') {
    $e.attr('model', 'left');
    _nowNex = 1;
    $(".right", $ep).hide();
    $e.append('<img src="img/title-2.jpg" remove="fadeOutRightBig" class="bn animated fadeInRightBig"/>');
    return changePoint('point4');
  } else if (fx === 'right') {
    $e.attr('model', 'right');
    _nowNex = 2;
    $(".left", $ep).hide();
    $e.append('<img src="img/title-3.jpg" remove="fadeOutLeftBig" class="bn animated fadeInLeftBig"/>');
    return changePoint('point5');
  } else if (fx === 'down') {
    $e.attr('model', 'down');
    return changePoint('point3');
  } else if (fx === 'up') {
    $e.attr('model', 'up');
    _nowNex = 3;
    $(".bottom", $ep).hide();
    $e.append('<img src="img/title-4.jpg" remove="fadeOutDownBig" class="bn animated fadeInUpBig"/>');
    return changePoint('point6');
  } else if (fx === 'up' && model === 'down') {
    $e.attr('model', 'center');
    return changePoint('point3');
  }
};

defaultNS = function(play) {
  var $e, $ep;
  if (play == null) {
    play = true;
  }
  _nowNex = 0;
  $e = $("#img-list .img-list");
  $e.attr('model', 'center');
  $ep = $("#img-list");
  $("[remove]", $ep).remove();
  $(".bottom,.left,.right", $ep).show();
  return changePoint('point3', play);
};

changePoint = function(p, play) {
  if (play == null) {
    play = true;
  }
  $("#pointinside").removeClass('point3 point4 point5 point6');
  $("#pointinside").addClass(p);
  return insideUserCtrl(play);
};

insideUserCtrl = function(play) {
  if (play == null) {
    play = true;
  }
  $("#pointinside .header").html(loading.list[_poList[_nowCar][_nowNex].header]);
  $("#pointinside .name h4").text(_poList[_nowCar][_nowNex].name);
  $("#pointinside .name p").text(_poList[_nowCar][_nowNex].title);
  console.log("can play", play);
  $("#audio")[0].pause();
  return showPlayGif();
};

fBindCarInside = function() {
  $(".interior").click(function() {
    console.log("interior", _animate);
    if (_animate) {
      return '';
    }
    _animate = true;
    $(".car360").removeClass('animated fadeOutRight fadeInLeft fadeInDownBig');
    $(".car360").addClass('animated fadeOutRight');
    $(".carsideinfo").removeClass('animated fadeOutRight fadeInLeft');
    $(".carsideinfo").show().addClass('animated fadeInLeft');
    _page = "interior";
    stopMove360();
    defaultNS();
    return setTimeout(function() {
      _animate = false;
      return $(".car360").hide();
    }, 500);
  });
  $(".exterior").click(function() {
    console.log("exterior", _animate);
    if (_animate) {
      return '';
    }
    _animate = true;
    _page = "360";
    $(".car360").removeClass('animated fadeOutRight fadeInLeft');
    $(".car360").show().addClass('animated fadeInLeft');
    $(".carsideinfo").removeClass('animated fadeOutRight fadeInLeft');
    $(".carsideinfo").addClass('animated fadeOutRight');
    autoAudioX();
    $("#list360 .car").hide();
    $("#list360 .car").eq(1).show();
    hidePoint();
    starMove360();
    return setTimeout(function() {
      _animate = false;
      $(".carsideinfo").hide();
      return defaultNS(false);
    }, 500);
  });
  return $(".drive").click(function() {});
};

_nowCar = 'a33';

show360car = function() {
  $(".homepage").removeClass("fadeOutUpBig fadeInDownBig").addClass('animated fadeOutUpBig');
  $(".car360,.carsideinfo,.car360inside,.resertpage").hide().removeClass('fadeInDownBig fadeOutRight fadeInLeft fadeOutUpBig');
  return $(".car360").show().addClass('animated fadeInDownBig');
};

_only = {
  "a32": true,
  "a33": true
};

create360Car = function(e) {
  var i, _i;
  _nowCar = e;
  console.log("page: ", _page);
  $("#list360 .imglist").html('');
  for (i = _i = 1; _i <= 12; i = ++_i) {
    $("#list360 .imglist").append("<img class='car' src='img/" + e + "/" + i + ".png' />");
  }
  $("#list360 .car").hide();
  $("#list360 .car").eq(1).show();
  if (_page === "360") {
    autoAudioX();
  } else {
    defaultNS();
  }
  hidePoint();
  if (_nowCar === 'a33') {
    return $("#back-image,#changed-image").attr('src', 'img/a3s-back.png');
  } else {
    return $("#back-image,#changed-image").attr('src', 'img/a3l-back.png');
  }
};

bindChangeCar = function() {
  return $(".car-back").click(function() {
    if (_nowCar === 'a33') {
      return create360Car('a32');
    } else {
      return create360Car('a33');
    }
  });
};

_x360 = 0;

_tmove = null;

_speedfor = 2000;

_stopmovenext = false;

stopMove360 = function() {
  _stopmovenext = true;
  return clearTimeout(_tmove);
};

startTimeGo = function() {
  var $e, time;
  time = _speedfor;
  if ($("#list360 .car:visible").next().is('.car')) {
    $e = $("#list360 .car:visible").next();
  } else {
    $e = $("#list360 .car:first");
  }
  if ($e.index() === 4 || $e.index() === 0) {
    time = time * 3;
  }
  if (_stopmovenext) {
    return '';
  }
  return _tmove = setTimeout(function() {
    showNext360Img();
    return startTimeGo();
  }, time);
};

starMove360 = function() {
  _stopmovenext = false;
  return startTimeGo();
};

bind360Car = function() {
  $("#list360")[0].addEventListener('touchstart', touch360carstart);
  $("#list360")[0].addEventListener('touchmove', touch360carmove);
  $("#list360")[0].addEventListener('touchend', touch360carend);
  return starMove360();
};

touch360carstart = function(e) {
  _x360 = e.touches[0].pageX;
  return stopMove360();
};

touch360carmove = function(e) {
  var abs, mx, x;
  e.preventDefault();
  x = e.touches[0].pageX;
  mx = Math.round(_x360 - x);
  abs = Math.abs(mx);
  if (mx >= 20) {
    showNext360Img();
    _x360 = e.touches[0].pageX;
  }
  if (mx <= -20) {
    showPrev360Img();
    return _x360 = e.touches[0].pageX;
  }
};

touch360carend = function(e) {
  console.log("start _tmove");
  return starMove360();
};

showNext360Img = function() {
  var $e;
  if ($("#list360 .car:visible").next().is('.car')) {
    $e = $("#list360 .car:visible").next();
    $("#list360 .car").hide();
    $e.show();
  } else {
    $e = $("#list360 .car:first");
    $("#list360 .car").hide();
    $e.show();
  }
  if ($e.index() === 11) {
    return showPoint(1);
  } else if ($e.index() === 3) {
    return showPoint(2);
  } else {
    return hidePoint();
  }
};

showPrev360Img = function() {
  var $e;
  if ($("#list360 .car:visible").prev().is('.car')) {
    $e = $("#list360 .car:visible").prev();
    $("#list360 .car").hide();
    $e.show();
  } else {
    $e = $("#list360 .car:last");
    $("#list360 .car").hide();
    $e.show();
  }
  if ($e.index() === 11) {
    return showPoint(1);
  } else if ($e.index() === 3) {
    return showPoint(2);
  } else {
    return hidePoint();
  }
};

hidePoint = function() {
  $("#point").hide();
  return $("#point").removeClass("animated tada");
};

_nowNet = 0;

showPoint = function(index) {
  $("#point").removeClass('point2 point3 point4');
  _nowNet = index - 1;
  if (index === 2) {
    $("#point").addClass('point2');
  }
  $("#point .header").html(loading.list[_pointList[_nowCar][index - 1].header]);
  $("#point .name h4").text(_pointList[_nowCar][index - 1].name);
  $("#point .name p").text(_pointList[_nowCar][index - 1].title);
  $("#times").text(_pointList[_nowCar][index - 1].times);
  console.log(_playingradio, _nowCar, _nowNet);
  if (_playingradio.car === _nowCar && _playingradio.idt === _nowNet) {
    $("#point .play").show();
  } else {
    $("#point .play").hide();
    console.log("playing this.");
  }
  $("#point").show();
  return $("#point").addClass("animated tada");
};

stopAllPlay = function() {
  $("#point .play").hide();
  $("#pointinside .play").hide();
  return $(".radioinfo .radio .play").hide();
};

auto2Audio = function() {
  var info;
  info = _poList[_nowCar][_nowNex];
  console.log(info.mp3, info.mp3 !== $("#audio").attr('src'));
  if (info.mp3 !== $("#audio").attr('src')) {
    $("#audio").attr('src', info.mp3);
  }
  return $("#audio")[0].play();
};

autoAudioX = function() {
  var info;
  return "";
  info = _pointList[_nowCar][1];
  _nowNet = 1;
  $("#audio").attr('src', info.mp3);
  return $("#audio")[0].play();
};

autoAudio = function() {
  var info;
  _only[_nowCar] = false;
  console.log(_nowCar, _nowNet);
  info = _pointList[_nowCar][_nowNet];
  console.log("click audio play", info.mp3 !== $("#audio").attr('src'));
  if (info.mp3 !== $("#audio").attr('src')) {
    $("#audio").attr('src', info.mp3);
  }
  return $("#audio")[0].play();
};

endAudio = function() {
  console.log("end play");
  return _playing = false;
};

pauseAudio = function() {
  _playing = false;
  return $("#audio")[0].pause();
};

showCarInside = function(side) {
  var bg, user;
  user = {};
  if (side === 'inside') {
    user = _poList[_nowCar][_nowNex];
    bg = "inside-" + (_nowNex + 1) + ".jpg";
  } else {
    user = _pointList[_nowCar][_nowNet];
    bg = _nowCar + "-" + (_nowNet + 1) + ".jpg";
  }
  console.log(bg);
  $(".car360inside").css({
    'background-image': "url(img/" + bg + ")"
  });
  $(".car360inside .qaright").remove();
  $(".car360inside .avatar").html($(loading.list[user.header]).clone());
  $(".car360inside .userinfo h3").text(user.name);
  $(".car360inside .userinfo p").text(user.title);
  $(".car360inside .radioinfo h4").text(user.t1);
  $(".car360inside .radioinfo p").text(user.t2);
  $(".car360inside .qa h2").text(user.t3);
  $(".car360inside .qa .question .item").eq(0).find("p").text(user.q1);
  $(".car360inside .qa .question .item").eq(1).find("p").text(user.q2);
  $(".car360inside .qa .question .item").eq(user.answer).append('<div class="qaright"><img src="img/qaright.png" /></div>');
  $(".car360inside .radio span").text(user.times);
  $(".car360inside").removeClass('animated fadeOutUpBig');
  $(".car360inside").show().addClass('animated fadeInDownBig');
  $("#audio").attr('src', user.mp3);
  return stopAllPlay();
};

fBindAudio = function() {
  $("#audio")[0].addEventListener("ended", audioEnded);
  $("#audio")[0].addEventListener("playing", audioPlaying);
  $("#audio")[0].addEventListener("pause", audioPause);
  return $(".radio").click(function() {
    if (_playing) {
      $("#audio")[0].pause();
      return audioEnded({});
    } else {
      $("#audio")[0].play();
      return $(".car360inside .radio .play").show();
    }
  });
};

audioPause = function(e) {
  console.log("播放暂停");
  _playing = false;
  _pause = true;
  return stopAllPlay();
};

audioPlaying = function(e) {
  _playingradio.car = _nowCar;
  _playingradio.idx = _nowNex;
  _playingradio.idt = _nowNet;
  console.log("播放", e);
  _playing = true;
  _pause = false;
  return showPlayGif();
};

audioEnded = function(e) {
  console.log("播放结束");
  $(".car360inside .radio .play").hide();
  _playing = false;
  _pause = false;
  _playingradio = {
    car: "",
    idx: -1,
    idt: -1
  };
  return stopAllPlay();
};

showPlayGif = function() {
  stopAllPlay();
  if (_playingradio.car === _nowCar && _playingradio.idx === _nowNex && _playing && !_pause) {
    $("#pointinside .play").show();
  }
  if (_playingradio.car === _nowCar && _playingradio.idt === _nowNet && _playing && !_pause) {
    $("#point .play").show();
  }
  if (_playing && !_pause && $(".car360inside").is(".fadeInDownBig")) {
    return $(".car360inside .radio .play").show();
  }
};

fBindQAanswer = function() {
  return $(".car360inside .item").click(function() {
    return $(".car360inside .item .qaright").show().addClass('animated fadeInLeft');
  });
};

backCarInside = function() {
  $(".car360inside").removeClass('animated fadeInDownBig');
  $(".car360inside").addClass('animated fadeOutUpBig');
  $("#audio")[0].pause();
  starMove360();
  return setTimeout(function() {
    return $(".car360inside").hide();
  }, 500);
};

bind360CarInside = function() {
  $("#point .header").click(function() {
    showCarInside('outside');
    return stopMove360();
  });
  $("#point .sound").click(function() {
    console.log(_playingradio, _nowCar, _nowNet, _playing);
    if (_playingradio.car === _nowCar && _playingradio.idt === _nowNet && _playing) {
      return pauseAudio();
    } else {
      console.log("run");
      return autoAudio();
    }
  });
  $("#pointinside .header").click(function() {
    return showCarInside('inside');
  });
  return $("#pointinside .sound").click(function() {
    if (_playing && _playingradio.car === _nowCar && _playingradio.idx === _nowNex && _playing) {
      return pauseAudio();
    } else {
      return auto2Audio();
    }
  });
};

playMusic = function(e) {
  var info;
  if (e === 1) {
    info = _pointList["a33"][0];
    $("#audio").attr('src', info.mp3);
    $("#audio")[0].play();
  }
  if (e === 2) {
    info = _pointList["a32"][0];
    $("#audio").attr('src', info.mp3);
    return $("#audio")[0].play();
  }
};

fBindFormBtn = function() {
  return $('[name=submit]').click(function() {
    var reg;
    if ($('[name=username]').val().length <= 0) {
      return alert('姓名不能为空');
    }
    if ($('[name=sex]').val().length <= 0) {
      return alert('请选择性别');
    }
    if ($('[name=mobile]').val().length <= 0) {
      return alert('手机号码不能为空');
    }
    if ($('[name=mobile]').val().length !== 11) {
      return alert('手机号码必须是11位数字');
    }
    if ($('[name=email]').val().length <= 0) {
      return alert('邮箱地址不能为空');
    }
    reg = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
    if (!reg.test($('[name=email]').val())) {
      return alert('邮箱格式不正确');
    }
    if ($('[name=cartype]').val().length <= 0) {
      return alert('请选择感兴趣车型');
    }
    if ($('[name=buytime]').val().length <= 0) {
      return alert('请选择购车意向');
    }
    if ($('[name=province]').val().length <= 0) {
      return alert('请选择省份');
    }
    if ($('[name=city]').val().length <= 0) {
      return alert('请选择城市');
    }
    if ($('[name=dealer]').val().length <= 0) {
      return alert('请选择经销商');
    }
    return $.ajax({
      type: "post",
      dataType: "json",
      url: "reservations.php",
      data: $('[name=register]').serializeArray(),
      success: function(msg) {
        if (msg.state === 'success') {
          alert('预约成功');
          return window.location.reload();
        } else {
          return alert(msg.msg);
        }
      }
    });
  });
};
