// Generated by CoffeeScript 1.7.1
var Locals;

Locals = (function() {
  function Locals(name) {
    this.name = name;
    this.isLocals = window.localStorage ? true : false;
  }

  Locals.prototype.set = function(key, value) {
    if (this.isLocals) {
      return window.localStorage.setItem(key, value);
    }
  };

  Locals.prototype.get = function(key) {
    if (this.isLocals) {
      return window.localStorage.getItem(key);
    }
  };

  Locals.prototype.remove = function(key) {
    if (this.isLocals) {
      return window.localStorage.removeItem(key);
    }
  };

  return Locals;

})();
