// Generated by CoffeeScript 1.7.1
var baiduMap;

baiduMap = (function() {
  var addMark;

  function baiduMap(name) {
    this.name = name;
    if (typeof BMap !== "undefined" && BMap !== null) {
      this.init(this.name);
    }
  }

  baiduMap.prototype._map = {};

  baiduMap.prototype._local = {};

  baiduMap.prototype._mycenter = {};

  baiduMap.prototype.Point = function(lng, lat) {
    if (lng == null) {
      lng = 116.404;
    }
    if (lat == null) {
      lat = 39.915;
    }
    return new BMap.Point(lng, lat);
  };

  baiduMap.prototype.init = function(id) {
    var center, map;
    map = this._map;
    map = new BMap.Map(id);
    center = this.Point();
    return map.centerAndZoom(center, 13);
  };

  baiduMap.prototype.search = function(keys, callback) {
    var local, reload_local;
    this._local = new BMap.LocalSearch(map, {
      renderOptions: {
        autoViewport: true
      }
    });
    local = this._local;
    local.searchNearby(myKeys, _mycenter);
    return reload_local(this._local, reload_local = function(sd, callback) {
      return setTimeout(function() {
        if (sd.length <= 0) {
          return reload_local(sd, callback);
        } else {
          return callback(sd);
        }
      }, 50);
    });
  };

  addMark = function(list) {
    var a, marker, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      a = list[_i];
      marker = new BMap.Marker(a.Point);
      _results.push(this._map.addOverlay(marker));
    }
    return _results;
  };

  return baiduMap;

})();
