// Generated by CoffeeScript 1.7.1
var MapMark;

MapMark = (function() {
  function MapMark(name) {
    this.name = name;
    this.init;
  }

  MapMark.prototype.init = function() {
    return alert('');
  };

  return MapMark;

})();
