// Generated by CoffeeScript 1.8.0
var parallax, readyLoaded, readyLoading, selectPaper, selectPoint, stopHeight, _stopHeight;

$(document).ready(function() {
  if ($(".page").height() < 450) {
    $("body").addClass("iphone4");
  }
  return $("[data-page]").click(function() {
    return parallax.runcode(parseInt($(this).attr("data-page")));
  });
});

selectPaper = function(e) {
  return $(".tabs").removeClass("on1 on2 on3 on4 on5").addClass("on" + e);
};

selectPoint = function(e) {
  $(e).removeClass("gray");
  if ($(".point.gray").length <= 0) {
    return setTimeout(function() {
      return $("#firebox").addClass("fireon").html('<img src="img/page-7-fire.png" />');
    }, 500);
  }
};

_stopHeight = false;

stopHeight = function() {
  var top;
  if (_stopHeight) {
    return "";
  }
  _stopHeight = true;
  top = $(".step-list").offset();
  return $(".page-content").css({
    "top": top.height + "px"
  });
};

readyLoaded = [];

readyLoading = function(index) {
  var e;
  if (readyLoaded[index] === "loaded") {
    return true;
  }
  e = $("section.page").eq(index);
  readyLoaded[index] = "loaded";
  e.find("[lz-src]").each(function(i) {
    $(this).attr("src", $(this).attr("lz-src"));
    return true;
  });
  return e.find("[data-page]").each(function(i) {
    readyLoading(-1 + parseInt($(this).attr("data-page")));
    return true;
  });
};

parallax = $('.pages').parallax({
  irection: 'vertical',
  drag: false,
  loading: false,
  indicator: false,
  arrow: false,
  onchange: function(index, element, direction) {
    readyLoading(index);
    return readyLoading(index + 2);
  },
  orientationchange: function(orientation) {}
});
