// Generated by CoffeeScript 1.7.1
var EditUploadFace, EditUploadHappyFace, Gameone, Gametwo, Queen, banner, bindUploadFile, canvas, changeface, clickbg, count, createActionone, createActiontwo, createGameOverContent, exportRoot, fileDown, fileMove, fileMoveOver, firstFrame, gameagain, gameoneOver, gametwoOver, gotoTick, handleComplete, handleFileLoad, handleLocalFile, hideMark, images, init, loadImg, loader, loadingTxt, manifest, myGetId, pauseactiontwo, playaction, playactiontwo, publicH, publicW, queen, removeMark, showUpload, stage, startFirstFrame, startGame, startUploadFace, startUploadHappyFace, stopaction, tempscale, tick, _act_dj, _act_shan, _cangoto, _defaultMove, _defaultscale, _defaultscale1, _defaultscale2, _dom_Bbegin, _dom_Bnext, _dom_banner, _dom_bg, _dom_border, _dom_btn_again, _dom_faceInfo1, _dom_faceInfo2, _dom_gamebg, _dom_gameone_text, _dom_gameover, _dom_gametwo_text, _dom_mark, _dom_mc1, _dom_pop1, _dom_pop2, _dom_queen, _dom_uploadText1, _dom_uploadText2, _dom_uploadfile1, _dom_uploadfile2, _dom_welcomeText, _facecenter, _faceovercenter, _game_one_over, _game_one_over_go, _hide_mark, _numdj, _remove_mark;

loader = {};

canvas = {};

stage = {};

exportRoot = {};

count = 0;

loadingTxt = "";

publicW = publicH = 640;

manifest = {};

images = {};

queen = {};

banner = {};

_facecenter = {
  x: 360,
  y: 460
};

_faceovercenter = {
  x: 310,
  y: 320
};

_dom_border = {};

_dom_bg = {};

_dom_banner = {};

_dom_Bbegin = {};

_dom_Bnext = {};

_dom_mark = {};

_dom_welcomeText = {};

_dom_mc1 = {};

_dom_queen = {};

_dom_uploadText1 = {};

_dom_uploadText2 = {};

_dom_uploadfile1 = {};

_dom_uploadfile2 = {};

_dom_faceInfo1 = [];

_dom_faceInfo2 = [];

_dom_gamebg = {};

_dom_pop1 = {};

_dom_pop2 = {};

_dom_gameone_text = {};

_dom_gametwo_text = {};

_dom_gameover = {};

_dom_btn_again = {};

_act_shan = {};

_act_dj = {};

_hide_mark = 0;

_remove_mark = false;

_defaultMove = 0;

_defaultscale = 1;

tempscale = 1;

_defaultscale1 = 1;

_defaultscale2 = 2;

myGetId = function(id) {
  return document.getElementById(id);
};

init = function() {
  publicH = document.body.clientHeight * 640 / document.body.clientWidth;
  canvas = myGetId('canvas');
  stage = new createjs.Stage(canvas);
  createjs.Touch.enable(stage);
  stage.enableMouseOver(10);
  stage.mouseMoveOutside = true;
  loadingTxt = new createjs.Text('', 'bold 24px Arial', '#000000');
  loadingTxt.x = 230;
  loadingTxt.y = 450;
  stage.addChild(loadingTxt);
  stage.update();
  loadImg();
  bindUploadFile();
  return gotoTick();
};

bindUploadFile = function() {
  myGetId('firstface').addEventListener('change', function(e) {
    var files;
    files = this.files;
    if (files.length > 0) {
      return handleLocalFile(files[0], 1);
    }
  });
  return myGetId('secondface').addEventListener('change', function(e) {
    var files;
    files = this.files;
    if (files.length > 0) {
      return handleLocalFile(files[0], 2);
    }
  });
};

loadImg = function() {
  images = images || {};
  manifest = [
    {
      src: "img/bg.jpg",
      id: "bg"
    }, {
      src: "img/banner.png",
      id: "banner"
    }, {
      src: "img/border.png",
      id: "border"
    }, {
      src: "img/btn-begin.png",
      id: "btn-begin"
    }, {
      src: "img/btn-next.png",
      id: "btn-next"
    }, {
      src: "img/btn-restart.png",
      id: "btn-restart"
    }, {
      src: "img/queen.png",
      id: "queen"
    }, {
      src: "img/mark.png",
      id: "mark"
    }, {
      src: "img/gamebg.png",
      id: "gamebg"
    }, {
      src: "img/game-1-1.png",
      id: "game-1-1"
    }, {
      src: "img/game-2-1.png",
      id: "game-2-1"
    }, {
      src: "img/game-1-2.png",
      id: "game-1-2"
    }, {
      src: "img/game-2-2.png",
      id: "game-2-2"
    }, {
      src: "img/game-over.png",
      id: "game-over"
    }, {
      src: "img/game-again.png",
      id: "game-again"
    }, {
      src: "img/share.png",
      id: "share"
    }, {
      src: "img/over-text.png",
      id: "over-text"
    }, {
      src: "img/action-shan.png",
      id: "action-shan"
    }, {
      src: "img/action-dj.png",
      id: "action-dj"
    }, {
      src: "img/chicken.png",
      id: "chicken"
    }
  ];
  loader = new createjs.LoadQueue(false);
  loader.installPlugin(createjs.Sound);
  loader.addEventListener("fileload", handleFileLoad);
  loader.addEventListener("complete", handleComplete);
  return loader.loadManifest(manifest);
};

handleFileLoad = function(evt) {
  $('#loading').hide();
  if (evt.item.type === "image") {
    images[evt.item.id] = evt.result;
  }
  count++;
  loadingTxt.text = "加载了: " + Math.floor(count / manifest.length * 100) + "%";
  stage.update();
  if (count === manifest.length) {
    return firstFrame();
  }
};

handleComplete = function(evt) {};

clickbg = function(e) {};

window.onload = function() {
  queen = new Queen();
  return init();
};

handleLocalFile = function(file, index) {
  var $img, url;
  if (index === 1) {
    stage.removeChild(_dom_uploadText1);
  } else {
    stage.removeChild(_dom_uploadText2);
  }
  url = webkitURL.createObjectURL(file);
  $img = new Image();
  $img.onload = function() {
    var deg;
    if (index === 1) {
      _dom_faceInfo1 = [
        {
          x: $img.width / 2,
          y: $img.height / 2,
          width: 1,
          height: 1
        }
      ];
      deg = 0;
      _dom_uploadfile1 = new createjs.Shape();
      _dom_uploadfile1.graphics.beginFill("#fff").drawRect(-1000, -1000, 3000, 3000).beginFill("#FFF");
      _dom_uploadfile1.alpha = 0.01;
      _dom_uploadfile1.cursor = "pointer";
      $img.id = "face1";
      $("#mubu").append($img);
      return EditUploadFace(deg);
    } else {
      _dom_faceInfo2 = [
        {
          x: $img.width / 2,
          y: $img.height / 2,
          width: 1,
          height: 1
        }
      ];
      deg = 0;
      _dom_uploadfile2 = new createjs.Shape();
      _dom_uploadfile2.graphics.beginFill("#fff").drawRect(-1000, -1000, 3000, 3000).beginFill("#FFF");
      _dom_uploadfile2.alpha = 0.01;
      _dom_uploadfile2.cursor = "pointer";
      $img.id = "face2";
      $("#mubu").append($img);
      return EditUploadHappyFace(deg);
    }
  };
  $img.src = url;
  return $(".firstframe,.secondframe").hide();
};

changeface = function(e) {};

gotoTick = function() {
  createjs.Ticker.setFPS(30);
  createjs.Ticker.addEventListener("tick", tick);
  return createjs.Ticker.addEventListener("tick", stage);
};

firstFrame = function() {
  var begin, bg, border, mark, mc, welcomeText;
  queen.init(images);
  stage.removeChild(loadingTxt);
  welcomeText = new createjs.Text('联想30年有你相伴\n今天你说了算', 'normal 36px MicrosoftYaHei', '#ffffff');
  welcomeText.textAlign = "center";
  welcomeText.setTransform(318, 500);
  border = queen.getDomBit("border");
  bg = queen.getDomBit("bg");
  mark = queen.getDomBit("mark");
  mark.setTransform(0, 0, 640, 920);
  banner = queen.getDomBit("banner");
  banner.setTransform(200, 180);
  begin = queen.getDomBit("btn-begin");
  begin.setTransform(220, 735);
  mc = new createjs.MovieClip(null, 0, true, {
    start: 0,
    middle: 50
  });
  mc.timeline.addTween(createjs.Tween.get(banner).to({
    y: 220
  }).to({
    y: 260
  }, 40).to({
    y: 220
  }, 40));
  mc.gotoAndPlay('middle');
  _dom_welcomeText = welcomeText;
  _dom_border = border;
  _dom_bg = bg;
  _dom_banner = banner;
  _dom_Bbegin = begin;
  _dom_mc1 = mc;
  _dom_mark = mark;
  _dom_gamebg = queen.getDomBit('gamebg');
  stage.removeAllChildren();
  stage.addChild(_dom_bg, _dom_Bbegin, _dom_mark, _dom_welcomeText, _dom_mc1, _dom_border);
  mark.addEventListener('click', startFirstFrame);
  return begin.addEventListener('pressup', startUploadFace);
};

startUploadFace = function() {
  var tixing;
  _dom_queen = queen.getDomBit('queen');
  _dom_banner.setTransform(20, 100);
  _dom_uploadText1 = new createjs.Text('上传生气的头像', 'normal 14px MicrosoftYaHei', '#000000');
  _dom_uploadText1.textAlign = "center";
  _dom_uploadText1.setTransform(308, 320);
  tixing = new createjs.Text('试试看拖动或者\n缩放你上传的照片', 'normal 18px MicrosoftYaHei', '#ffffff');
  tixing.textAlign = "center";
  tixing.setTransform(318, 770);
  stage.removeAllChildren();
  stage.addChild(_dom_gamebg, _dom_uploadText1, tixing, _dom_border, _dom_mc1);
  return showUpload("first");
};

showUpload = function(text) {
  return setTimeout(function() {
    return $("." + text + "frame").show();
  }, 500);
};

EditUploadFace = function(deg) {
  var a, img, scale;
  _dom_Bnext = queen.getDomBit('btn-next');
  _dom_Bnext.setTransform(220, 735);
  deg = 0;
  scale = 1;
  a = _dom_uploadfile1;
  img = a.image;
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile1, _dom_gamebg, _dom_Bnext, _dom_border, _dom_mc1);
  _dom_uploadfile1.addEventListener("mousedown", fileDown);
  _dom_uploadfile1.addEventListener("pressmove", fileMove);
  _dom_uploadfile1.addEventListener("pressup", fileMoveOver);
  return _dom_Bnext.addEventListener("click", startUploadHappyFace);
};

startUploadHappyFace = function() {
  var tixing;
  $("#face1").hide();
  _defaultscale1 = _defaultscale;
  _defaultMove = 0;
  _defaultscale = 1;
  tempscale = 1;
  stage.removeAllChildren();
  _dom_uploadText2 = new createjs.Text('上传开心的头像', 'normal 14px MicrosoftYaHei', '#000000');
  _dom_uploadText2.textAlign = "center";
  _dom_uploadText2.setTransform(308, 320);
  tixing = new createjs.Text('试试看拖动或者\n缩放你上传的照片', 'normal 18px MicrosoftYaHei', '#ffffff');
  tixing.textAlign = "center";
  tixing.setTransform(318, 770);
  stage.addChild(_dom_gamebg, _dom_uploadText2, tixing, _dom_border, _dom_mc1);
  return showUpload("second");
};

EditUploadHappyFace = function(deg) {
  var a, img, scale;
  _dom_Bnext.removeEventListener("click", startUploadHappyFace);
  deg = 0;
  scale = 1;
  a = _dom_uploadfile2;
  img = a.image;
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile2, _dom_gamebg, _dom_Bnext, _dom_border, _dom_mc1);
  _dom_uploadfile2.addEventListener("mousedown", fileDown);
  _dom_uploadfile2.addEventListener("pressmove", fileMove);
  _dom_uploadfile2.addEventListener("pressup", fileMoveOver);
  return _dom_Bnext.addEventListener("click", startGame);
};

startGame = function() {
  var random;
  $("#face1").show();
  $("#face2").hide();
  random = Math.random() * 100;
  if (random > 49) {
    return Gameone();
  } else {
    return Gametwo();
  }
};

Gametwo = function() {
  var _dom_gametwo_stuff1;
  createActiontwo();
  _dom_gametwo_stuff1 = queen.getDomBit('chicken');
  _dom_gametwo_stuff1.setTransform(300, 705);
  _dom_gameone_text = new createjs.Text('点击小人开始倒酒', 'normal 24px MicrosoftYaHei', '#ffffff');
  _dom_gameone_text.textAlign = "center";
  _dom_gameone_text.setTransform(310, 790);
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile1, _dom_gamebg, _dom_gametwo_stuff1, _act_dj, _dom_pop1, _dom_gameone_text, _dom_border);
  _act_dj.addEventListener('pressup', playactiontwo);
  _dom_uploadfile1.removeEventListener("mousedown", fileDown);
  _dom_uploadfile1.removeEventListener("pressmove", fileMove);
  _dom_uploadfile1.removeEventListener("pressup", fileMoveOver);
  _dom_uploadfile2.removeEventListener("mousedown", fileDown);
  _dom_uploadfile2.removeEventListener("pressmove", fileMove);
  return _dom_uploadfile2.removeEventListener("pressup", fileMoveOver);
};

_numdj = 0;

_cangoto = true;

playactiontwo = function() {
  if (_cangoto) {
    _numdj++;
    _act_dj.play();
    _dom_gameone_text.text = "再倒" + (5 - _numdj) + "杯";
    if (_numdj === 3) {
      _dom_gameone_text.text = "继续点击";
    }
    if (_numdj === 4) {
      stage.removeChild(_dom_pop1);
      stage.addChild(_dom_pop2);
    }
    if (_numdj >= 5) {
      return gametwoOver();
    }
    _cangoto = false;
    return setTimeout(function() {
      return pauseactiontwo();
    }, 500);
  }
};

pauseactiontwo = function() {
  _act_dj.gotoAndStop(0);
  return _cangoto = true;
};

Gameone = function() {
  createActionone();
  _dom_gameone_text = new createjs.Text('按住屏幕3秒给女王降降温', 'normal 24px MicrosoftYaHei', '#ffffff');
  _dom_gameone_text.textAlign = "center";
  _dom_gameone_text.setTransform(348, 670);
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile1, _dom_gamebg, _act_shan, _dom_pop1, _dom_gameone_text, _dom_border);
  _dom_gamebg.addEventListener('mousedown', playaction);
  _dom_gamebg.addEventListener('pressup', stopaction);
  _dom_uploadfile1.removeEventListener("mousedown", fileDown);
  _dom_uploadfile1.removeEventListener("pressmove", fileMove);
  _dom_uploadfile1.removeEventListener("pressup", fileMoveOver);
  _dom_uploadfile2.removeEventListener("mousedown", fileDown);
  _dom_uploadfile2.removeEventListener("pressmove", fileMove);
  return _dom_uploadfile2.removeEventListener("pressup", fileMoveOver);
};

_game_one_over = false;

_game_one_over_go = {};

playaction = function() {
  _game_one_over_go = setTimeout(function() {
    _dom_gamebg.removeEventListener('pressup', stopaction);
    return gameoneOver();
  }, 3000);
  _act_shan.play();
  stage.removeChild(_dom_pop1, _dom_gameone_text);
  return stage.addChild(_dom_pop2);
};

stopaction = function() {
  clearTimeout(_game_one_over_go);
  _act_shan.gotoAndStop(0);
  stage.removeChild(_dom_pop2);
  return stage.addChild(_dom_pop1);
};

createActionone = function() {
  var feng, grant;
  feng = new createjs.SpriteSheet({
    "animations": {
      "run": [0, 1, "run"]
    },
    "images": ["img/action-shan.png"],
    "frames": {
      "height": 400,
      "width": 340,
      "regX": 0,
      "regY": 0,
      "count": 2
    }
  });
  grant = new createjs.Sprite(feng);
  grant.x = 10;
  grant.y = 450;
  _act_shan = grant;
  _dom_pop1 = queen.getDomBit("game-1-1");
  _dom_pop1.setTransform(20, 290);
  _dom_pop2 = queen.getDomBit("game-1-2");
  _dom_pop2.setTransform(20, 290);
  _dom_gameover = queen.getDomBit("game-over");
  return _dom_gameover.setTransform(20, 290);
};

createActiontwo = function() {
  var feng, grant;
  feng = new createjs.SpriteSheet({
    "framerate": 20,
    "animations": {
      "run": [0, 1, "run"]
    },
    "images": ["img/action-dj.png"],
    "frames": {
      "height": 340,
      "width": 250,
      "regX": 0,
      "regY": 0,
      "count": 2
    }
  });
  grant = new createjs.Sprite(feng);
  grant.x = 395;
  grant.y = 430;
  _act_dj = grant;
  _dom_pop1 = queen.getDomBit("game-2-1");
  _dom_pop1.setTransform(20, 290);
  _dom_pop2 = queen.getDomBit("game-2-2");
  _dom_pop2.setTransform(20, 290);
  _dom_gameover = queen.getDomBit("game-over");
  return _dom_gameover.setTransform(20, 290);
};

createGameOverContent = function() {};

gametwoOver = function() {
  var mark, overtext, sharetext;
  $("#face1").fadeOut(500);
  $("#face2").fadeIn(500);
  mark = new createjs.Shape(new createjs.Graphics().beginFill("#000000").drawRect(0, 0, 640, 920));
  mark.set({
    alpha: 0.5
  });
  overtext = queen.getDomBit('over-text');
  overtext.setTransform(32.5, 500);
  sharetext = queen.getDomBit('share');
  sharetext.setTransform(445, 35);
  _dom_btn_again = queen.getDomBit('game-again');
  _dom_btn_again.setTransform(218.5, 705);
  _dom_btn_again.addEventListener('pressup', gameagain);
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile2, _dom_gamebg, _act_dj, _dom_gameover, mark, overtext, _dom_btn_again, sharetext, _dom_border);
  _act_dj.removeEventListener('pressup', playactiontwo);
  return _dom_Bnext.removeEventListener("click", startGame);
};

gameoneOver = function() {
  var mark, overtext, sharetext;
  $("#face1").fadeOut(500);
  $("#face2").fadeIn(500);
  mark = new createjs.Shape(new createjs.Graphics().beginFill("#000000").drawRect(0, 0, 640, 920));
  mark.set({
    alpha: 0.5
  });
  overtext = queen.getDomBit('over-text');
  overtext.setTransform(32.5, 500);
  sharetext = queen.getDomBit('share');
  sharetext.setTransform(445, 35);
  _dom_btn_again = queen.getDomBit('game-again');
  _dom_btn_again.setTransform(218.5, 705);
  _dom_btn_again.addEventListener('pressup', gameagain);
  stage.removeAllChildren();
  stage.addChild(_dom_uploadfile2, _dom_gamebg, _act_shan, _dom_gameover, mark, overtext, _dom_btn_again, sharetext, _dom_border);
  _dom_gamebg.removeEventListener('mousedown', playaction);
  _dom_gamebg.removeEventListener('pressup', stopaction);
  return _dom_Bnext.removeEventListener("click", startGame);
};

gameagain = function() {
  $("#face1").hide();
  $("#face2").hide();
  return window.location.reload();
};

fileDown = function(evt) {
  var o;
  o = evt.target;
  o.offset = {
    x: o.x - evt.stageX,
    y: o.y - evt.stageY
  };
  return true;
};

fileMove = function(evt) {
  var a, b, demov, o, scale, x, y;
  o = evt.target;
  if (evt.nativeEvent && evt.nativeEvent.targetTouches && evt.nativeEvent.targetTouches.length > 1) {
    a = evt.nativeEvent.targetTouches[0];
    b = evt.nativeEvent.targetTouches[1];
    x = a.clientX - b.clientY;
    y = a.clientY - b.clientY;
    x = x > 0 ? x : -x;
    y = y > 0 ? y : -y;
    demov = Math.sqrt(x * x + y * y);
    if (_defaultMove === 0) {
      _defaultMove = demov;
      return true;
    }
    scale = (demov - _defaultMove) * 0.2;
    tempscale = _defaultscale + scale / 100;
    if ($("#face1").is(':visible')) {
      $("#face1").css({
        "transform": "scale(" + tempscale + ")"
      });
    }
    if ($("#face2").is(':visible')) {
      $("#face2").css({
        "transform": "scale(" + tempscale + ")"
      });
    }
  } else if (_defaultMove !== 0) {

  } else {
    o.x = evt.stageX + o.offset.x;
    o.y = evt.stageY + o.offset.y;
  }
  if ($("#face1").is(':visible')) {
    $("#face1").css({
      left: o.x + "px",
      top: o.y + "px"
    });
  }
  if ($("#face2").is(':visible')) {
    $("#face2").css({
      left: o.x + "px",
      top: o.y + "px"
    });
  }
  return true;
};

fileMoveOver = function(evt) {
  if (evt.nativeEvent.targetTouches.length <= 0) {
    _defaultMove = 0;
    return _defaultscale = tempscale;
  }
};

startFirstFrame = function(mark) {
  return _hide_mark = 0.025;
};

tick = function(event) {
  var deltaS;
  deltaS = event.delta / 1000;
  if (_hide_mark && !(_hide_mark >= 1)) {
    _hide_mark += 0.05;
    hideMark();
  } else if (_hide_mark >= 1 && !_remove_mark) {
    removeMark();
  }
  return stage.update(event);
};

removeMark = function() {
  var mark, text;
  mark = _dom_mark;
  text = _dom_welcomeText;
  stage.removeChild(mark, text);
  return stage.update();
};

hideMark = function() {
  var mark, text, value;
  value = Math.sin(_hide_mark) * 360;
  mark = _dom_mark;
  text = _dom_welcomeText;
  mark.setTransform(mark.x, mark.y, mark.scaleX, mark.scaleY);
  text.setTransform(text.x, text.y, text.scaleX, text.scaleY, value);
  text.scaleX -= 0.05;
  text.scaleY -= 0.05;
  mark.scaleX = 640 - (_hide_mark * 640);
  mark.scaleY = 920 - (_hide_mark * 920);
  mark.x = _hide_mark * 320;
  return mark.y = _hide_mark * 920 / 2;
};

Queen = (function() {
  function Queen() {}

  Queen.prototype.images = [];

  Queen.prototype.init = function(images) {
    return this.images = images;
  };

  Queen.prototype.getDomBit = function(name) {
    var hill;
    hill = new createjs.Bitmap(loader.getResult(name));
    return hill;
  };

  Queen.prototype.getDom = function(name, x, y) {
    var data, dom, spriteSheet;
    if (x == null) {
      x = 0;
    }
    if (y == null) {
      y = 0;
    }
    console.log;
    data = {
      images: [this.images[name]],
      frames: {
        width: this.images[name].width,
        height: this.images[name].height
      }
    };
    spriteSheet = new createjs.SpriteSheet(data);
    dom = new createjs.Sprite(spriteSheet);
    dom.x = x;
    dom.y = y;
    return dom;
  };

  Queen.prototype.findDom = function(name) {
    var a, _i, _len, _ref;
    _ref = this.doms;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      a = _ref[_i];
      return a.dom;
    }
    return false;
  };

  Queen.prototype.removeDom = function(name) {
    stage.removeChild(this.findDom(name).dom);
    return stage.update();
  };

  return Queen;

})();
