// Generated by CoffeeScript 1.8.0
var BindShare, fShare, reloadWechat, shareFriend, shareTimeline, _wechat, _wechat_bool, _wechat_f;

_wechat_f = {
  "appid": "",
  "img_url": "",
  "img_width": 200,
  "img_height": 200,
  "link": "",
  "desc": "",
  "title": ""
};

_wechat = {
  "appid": "",
  "img_url": "",
  "img_width": 200,
  "img_height": 200,
  "link": "",
  "desc": "",
  "title": ""
};

_wechat_bool = false;

reloadWechat = function() {
  shareFriend();
  return shareTimeline();
};

shareFriend = function() {
  if (window.WeixinJSBridge) {
    WeixinJSBridge.invoke('sendAppMessage', _wechat_f);
  }
  return document.title = _wechat_f.title;
};

shareTimeline = function() {
  if (window.WeixinJSBridge) {
    WeixinJSBridge.invoke('shareTimeline', _wechat);
  }
  return document.title = _wechat.title;
};

document.addEventListener('WeixinJSBridgeReady', function() {
  _wechat_bool = true;
  WeixinJSBridge.on('menu:share:appmessage', function(argv) {
    return shareFriend();
  });
  return WeixinJSBridge.on('menu:share:timeline', function(argv) {
    return shareTimeline();
  });
});

BindShare = function(content, url, pic) {
  var list;
  if (url == null) {
    url = window.location.href;
  }
  list = {
    "qweibo": "http://v.t.qq.com/share/share.php?title={title}&url={url}&pic={pic}",
    "renren": "http://share.renren.com/share/buttonshare.do?title={title}&link={url}&pic={pic}",
    "weibo": "http://v.t.sina.com.cn/share/share.php?title={title}&url={url}&pic={pic}",
    "qzone": "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url={url}&title={title}&pics={pic}",
    "facebook": "http://www.facebook.com/sharer/sharer.php?s=100&p[url]={url}}&p[title]={title}&p[summary]={title}&pic={pic}",
    "twitter": "https://twitter.com/intent/tweet?text={title}&pic={pic}",
    "kaixin": "http://www.kaixin001.com/rest/records.php?content={title}&url={url}&pic={pic}",
    "douban": "http://www.douban.com/share/service?bm=&image={pic}&href={url}&updated=&name={title}"
  };
  return $("a[data-share]").each(function(e) {
    return $(this).attr("href", fShare(list[$(this).data('share')], content, url, pic));
  });
};

fShare = function(url, content, sendUrl, pic) {
  var backUrl, shareContent;
  if (pic == null) {
    pic = "";
  }
  content = content;
  shareContent = encodeURIComponent(content);
  pic = encodeURIComponent(pic);
  url = url.replace("{title}", shareContent);
  url = url.replace("{pic}", pic);
  backUrl = encodeURIComponent(sendUrl);
  url = url.replace("{url}", backUrl);
  return url;
};
