// Generated by CoffeeScript 1.6.3
var Giccoo, gico;

Giccoo = (function() {
  function Giccoo(name) {
    this.name = name;
    this.checkOrientation();
  }

  Giccoo.prototype.weixin = function(callback) {
    return document.addEventListener('WeixinJSBridgeReady', callback);
  };

  Giccoo.prototype.checkOrientation = function() {
    var orientationChange, reloadmeta;
    orientationChange = function() {
      switch (window.orientation) {
        case 0:
          return reloadmeta(640, 0);
        case 90:
          return reloadmeta(641, "no");
        case -90:
          return reloadmeta(641, "no");
      }
    };
    reloadmeta = function(px, us) {
      return setTimeout(function() {
        var viewport;
        viewport = document.getElementById("viewport");
        return viewport.content = "width=" + px + ", user-scalable=" + us + ", target-densitydpi=device-dpi";
      }, 100);
    };
    window.addEventListener('load', function() {
      orientationChange();
      return window.onorientationchange = orientationChange;
    });
    return window.addEventListener("load", function() {
      return setTimeout(function() {
        return window.scrollTo(0, 1);
      });
    });
  };

  Giccoo.prototype.BindShare = function(content, url) {
    var $ep, list;
    if (url == null) {
      url = window.location.href;
    }
    $ep = this;
    list = {
      "qweibo": "http://v.t.qq.com/share/share.php?title={title}&url=",
      "renren": "http://share.renren.com/share/buttonshare.do?title={title}&link={url}",
      "weibo": "http://v.t.sina.com.cn/share/share.php?title={title}&url=",
      "qzone": "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url={url}&title={title}"
    };
    return $('a[data-share]').click(function() {
      return $ep.fShare(list[$(this).data('share')], content, url);
    });
  };

  Giccoo.prototype.fShare = function(url, content, sendUrl) {
    var backUrl, pic, shareContent;
    content = content.val();
    shareContent = encodeURIComponent(content);
    pic = '';
    url = url.replace("{title}", shareContent);
    backUrl = encodeURIComponent(sendUrl);
    url = url.replace("{url}", backUrl);
    return window.open(url, '_blank');
  };

  return Giccoo;

})();

gico = new Giccoo('normal');


/* --------------------------------------------
     Begin main.coffee
--------------------------------------------
*/

$(document).ready(function() {});
